name: Bug Report

description: "Create a report to help us improve"

labels: 
  - bug

assignees: 

title: "[BUG]"

body:
  required: true
  description: "Please provide a clear and concise description of the bug."

steps:
  - name: "Steps to Reproduce"
    description: "Please provide detailed steps to reproduce the bug."
    required: true
  - name: "Expected Behavior"
    description: "Please describe what you expected to happen."
    required: true
  - name: "Actual Behavior"
    description: "Please describe what actually happened."
    required: true
  - name: "Screenshots"
    description: "Please attach any relevant screenshots or videos that may help to understand the bug."

additional_information:
  - name: "Environment"
    description: "Please provide the following information:"
    fields:
      - name: "Operating System"
        description: "Please specify the name and version of your operating system."
        required: true
      - name: "Browser"
        description: "Please specify the name and version of the browser you were using."
        required: true
      - name: "Additional Information"
        description: "Please provide any additional information that you think might be helpful to understand the bug."
    required: true
  - name: "Severity"
    description: "Please select the severity of the bug."
    input_type: dropdown
    options:
      - "Critical"
      - "High"
      - "Medium"
      - "Low"
      - "Cosmetic"
  - name: "Reproducibility"
    description: "Please select how often you are able to reproduce the bug."
    input_type: dropdown
    options:
      - "Always"
      - "Intermittent"
      - "Rarely"
  - name: "Additional Notes"
    description: "Please provide any additional notes or comments about the bug that you think might be helpful."
    input_type: textarea
    required: false
