name: Bug Report

description: Create a report to help us improve

labels:
  - bug

assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Please provide a clear and concise description of the bug.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a detailed description of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the bug.
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: Please describe what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: Please describe what actually happened.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please attach any relevant screenshots or videos that may help to understand the bug.
